export const sponsors = [
  {
    href: "https://www.loadview-testing.com/",
    src: "https://i.imgur.com/iHdPKSV.png",
    alt: "LoadView-Testing",
  },
  {
    href: "https://420couponcodes.com/",
    src: "https://i.imgur.com/IbhCD2k.png",
    alt: "420couponcodes.com",
  },
  {
    href: "https://www.credimaxx.de/",
    src: "https://i.imgur.com/sf5e7KT.png",
    alt: "credimaxx.de",
  },
  {
    href: "https://www.top5credits.com/",
    src: "https://i.imgur.com/K2EU3HD.png",
    alt: "top5credits.com",
  },
  {
    href: "https://www.ramotion.com/agency/web-design/",
    src: "https://i.imgur.com/mQxmvRm.png",
    alt: "Ramotion",
  },
  {
    href: "https://www.softwaredevelopment.co.uk/",
    src: "https://i.imgur.com/HoU15ep.png",
    alt: "SoftwareDevelopmentUK",
  },
  {
    href: "https://theymakedesign.com/best-web-design-companies-3ecc85b32071",
    src: "https://i.imgur.com/kfA0vQE.png",
    alt: "theymakedesign.com",
  },
  {
    href: "https://www.instinctools.com/cloud-computing/",
    src: "https://i.imgur.com/c56Di42.png",
    alt: "*instinctools",
  },
  {
    href: "https://www.cryptonewsz.com/",
    src: "https://i.imgur.com/sYNDuyj.png",
    alt: "CryptoNewsZ",
  },
  {
    href: "https://legalbet.uk/",
    src: "https://i.imgur.com/2qQ6Gxf.png",
    alt: "Legalbet",
  },
  {
    href: "https://vpn-review.com/",
    src: "https://i.imgur.com/INf1G7H.png",
    alt: "VPN reviews 2019",
  },
  {
    href: "https://faveable.com/",
    src: "https://i.imgur.com/PMqdGyT.png",
    alt: "Faveable",
  },
  {
    href: "https://iboysoft.com",
    src: "https://i.imgur.com/eOWcxUr.png",
    alt: "iBoysoft",
  },
  {
    href: "https://sprocketdigital.co.nz/",
    src: "https://i.imgur.com/koJsb0d.png",
    alt: "Matthew Chalk",
  },
  {
    href: "https://webpundits.in",
    src: "https://i.imgur.com/IVgnquz.png",
    alt: "Buy RDP online from Web Pundits",
  },
];

export const supporters = [
  { href: "https://veepn.com/vpn-apps/vpn-for-chrome/", name: "VeePN VPN" },
  { href: "https://www.partitionwizard.com", name: "Partition Wizard" },
  { href: "https://www.minitool.com", name: "MiniTool" },
  { href: "http://www.metrodetroitreview.com", name: "metrodetroitreview.com" },
  { href: "https://kafidoff.com/", name: "Vasyl Kafidov" },
  { href: "https://www.appdrawn.com/", name: "AppDrawn" },
  { href: "https://www.butikkene.no/", name: "Butikkene.no" },
  { href: "https://swiindex.com/", name: "swiindex.com" },
  {
    href: "https://www.plumbingnewsandmore.com/",
    name: "Plumbing News and More",
  },
  { href: "https://www.edwinsedibles.com", name: "CBD Gummies" },
  { href: "https://cyberogism.com/", name: "Cyberogism" },
  {
    href: "http://www.fiveguysplumbingdearborn.com",
    name: "Five Guys Plumbing Dearborn",
  },
  { href: "https://talousapu.fi/", name: "Talousapu.fi" },
  { href: "https://www.glassesonweb.com/", name: "GlassesOnWeb.com" },
  { href: "https://www.arkiraha.fi/", name: "Arkiraha" },
  { href: "https://quickbookstoolhub.com/", name: "Quickbooks Tool Hub" },
  { href: "https://oscollective.org/", name: "Open Source Collective" },
  { href: "https://www.ibeesoft.com/", name: "iBeesoft" },
  { href: "https://legalbet.uk/", name: "Legalbet" },
  { href: "https://www.mister-auto.com/", name: "Mister Auto" },
  { href: "https://www.richmondconcretepros.com/", name: "Richmond Concrete" },
  { href: "https://tankpenge.dk", name: "Per Andersen" },
  { href: "https://www.refermate.com", name: "Refermate" },
  {
    href: "https://www.bathroomremodelingwesterville.com",
    name: "Bathroom Remodeling Westerville",
  },
  { href: "https://www.tankcoffee.com", name: "Tank Coffee" },
  { href: "https://www.easeus.de/", name: "EaseUS Germany" },
  { href: "https://rantent.com/", name: "Rantent" },
  { href: "https://rekteddies.com/", name: "Rekt Eddie's" },
  { href: "https://www.firesticktricks.com", name: "Fire Stick Tricks" },
  { href: "https://www.upgrow.com/", name: "UpGrow" },
  { href: "https://slex.io/", name: "SLEX" },
  { href: "https://truealtitude.shop/", name: "True Altitude" },
  {
    href: "https://www.globalsoftwarecompanies.com/",
    name: "Global Software Companies",
  },
  { href: "https://www.troupon.com", name: "Troupon" },
  { href: "https://minneapolistowingmn.com/", name: "Minneapolis Towing" },
  {
    href: "https://bestcryptofuturestradingplatform.com/",
    name: "Crypto Futures Trading Platforms",
  },
  { href: "https://earthweb.com/", name: "EarthWeb" },
  { href: "https://bountii.coupons/", name: "Bountii" },
  { href: "https://www.socialfollowers.uk/", name: "Social follower" },
];
